#!/bin/bash

let var=$1+$2

echo "we added your inputs and it returned ${var}"

if test $1 -gt $2;then

echo "you put the big one first"

elif test $1 -lt $2;then

echo "the larger one came second"

else 

echo "they the same ass numah bro"

fi
