#!/bin/bash
for (( i=1; i<=5; i++ )); do
let k=$i*4
for (( j=1; j<=3; j++ )); do
cat cars | cut -f $j | head -n $k | tail -n 4 | tr -d ',' | tr '\n' ',' | sed 's/ ,/,/g' | sed 's/,$/\n/g' >> newcars
done
done
