#!/bin/bash
#	Robin Kuhns
#	0467292
#	
#	Working

#count how many fields there are in the file
fields=$(head -1 $1 | wc -w) 

cat $1 | cut -f6 | sort -u > temp

#count how many lines are in file
lines=$(wc -l temp | cut -f1 --delimiter=' ')

#create menu
for (( i=1; i<=$lines; i++ )); do
room=$(head -n$i temp | tail -n1)

room=$(head -n$i temp |tail -n1)
sections=$(cat $1 | cut -f6 | grep $room | wc -l | cut -f1 --delimiter=' ')

printf "$room\t$sections\n" >>  temp2

done

cat temp2 | sort -k2 -r

#Clean up, clean up, everybody, everywhere, clean up, clean up, everybody do you your share!
rm temp
rm temp2
